### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by glprchs** [Wildboar-Software/pp#3]
Hello,
I'm getting an error when compiling ./make in Building part documentation.
I seem to be missing a module 
[pp@localhost pp]$ ./make > 20240712.make.log
In the file included from tb_dbm.c:19:
../../h/dbase.h:42:17: fatal error: ndbm.h : No file or folder of this type
   42 | #include "ndbm.h"
Thank you for your help
Best regards.

**Comment by glprchs** [comment]
I solved the error messages by installing the missing libraries.
For your information, I'm on Rocky Linux 9.4
https://github.com/LuaDist/libgdbm

**Comment by JonathanWilbur** [comment]
Hey there, my apologies for not getting back with you sooner. I recently gained a new child, so I've been sleepless and busy for the past few days. This does require that library, which I will add to the documentation.

You can see this library getting installed in the Dockerfile [here](https://github.com/Wildboar-Software/pp/blob/d3d1a47da88c8e1bef48b94e734499a614246058/pp.dockerfile#L9).

Anyway, glad you figured it out. Enjoy!

**Comment by glprchs** [comment]
Hello again,

I didn't notice any other error messages during the previous compilation although there were some, sorry. Apparently I'm still missing a library, so I've gone into the details and the code to find out more precisely where the problem could be.

in : /GitHub/pp/Tools/tables/tjoin 

[pp@# tjoin]$ cc   tjoin1.o tjoin2.o tjoin3.o lex.o tjoin.o -ll -o xtjoin
/usr/bin/ld : cannot find -ll
collect2: error: ld has returned exit status 1

[pp@# tjoin]$ cc   tjoin1.o tjoin2.o tjoin3.o lex.o tjoin.o -o xtjoin
/usr/bin/ld : lex.o : in the function « yylex » :
/home/pp/GitHub/pp/Tools/tables/tjoin/<stdout>:863 : indefined reference to « yywrap »
collect2: error: ld has returned exit status 1

I can't find out what "-ll" could be

Thank you for your help
BR.

**Comment by JonathanWilbur** [comment]
I am swamped at the moment, but I would guess that comes from GNU Flex. See if you have flex / and the dev package installed.

**Comment by glprchs** [comment]
flex is allready installed, but can't find flex-dev or flex-devel, It's part of PowerTools under Rocky Linux 8 but for the moment I can't find the corresponding version for Rocky Linux 9.
I'll keep digging ;)

**Comment by JonathanWilbur** [comment]
Are you using a strange C compiler per chance?

**Comment by glprchs** [comment]
I'm well aware that the easiest thing would be to use a developer OS in which everything would be understood and available, but I don't want to because, for security reasons, I generally use the minimum versions of OSes, and then I only add what I'm supposed to need, hence the error messages. But I'll get there, I'm sure.

**Comment by glprchs** [comment]
I've found it and I no longer get an error message when I compile. That's what I thought, I was missing a library
[libfl-static-2.6.4-9.el9.x86_64.rpm](https://download.rockylinux.org/vault/rocky/9.4/CRB/x86_64/os/Packages/l/libfl-static-2.6.4-9.el9.x86_64.rpm)
after recompiling, I no longer get any error messages.
